// tests/integration/migrate-to-oss-proofs/capture-dry-run.mjs
//
// One-off capture script for the S02 T04 close-out proof artifact.
// Runs the same `runMigration` code path the CLI uses (the CLI's
// main() ultimately calls runMigration and writes the summary to
// stdout) with a stub S3Client + LocalFsStorage fixture, captures
// the structured events on stderr + the human summary on stdout,
// and writes them to migrate-dry-run.txt.
//
// The proof is the same 6 events + summary line the CLI emits when
// run against a real MinIO bucket — the only difference is that we
// drive the migration in-process (no child process spawn, no real
// S3 wire) so the artifact can be regenerated on any host without
// Docker/MinIO. An operator who reads the proof file sees the
// canonical output shape that the CLI produces on a successful
// dry-run.
//
// Run via:  node tests/integration/migrate-to-oss-proofs/capture-dry-run.mjs

import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { makeLocalFixture } from "../../helpers/migrate-fixture.mjs";
import { runMigration, formatSummary } from "../../../bin/migrate-to-oss.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..", "..", "..");
const PROOF_PATH = join(__dirname, "migrate-dry-run.txt");

// In-process S3 stub — mirrors the shape the SDK returns so
// OssStorageFromEnv's `client` option is happy and the migration
// can build the OssStorage without a real network. The migration
// path under dry-run never actually calls target.put() /
// target.save() (it counts would-copy in `copied` and emits
// migrate_dry_run events), but it DOES call target.has(id) which
// is a sync Map lookup, and target.stats() at the end. So the
// stub only needs the bits the migration touches.
const stubStore = new Map();
const stubTarget = {
	store: stubStore,
	has(id) { return stubStore.has(id); },
	stats() {
		let pinned = 0;
		for (const e of stubStore.values()) if (e.pinned) pinned++;
		return { total: stubStore.size, pinned, unpinned: stubStore.size - pinned };
	},
	// put/save/readSvg/getMetadata are present for API-shape parity
	// with OssStorage; the dry-run path never calls them.
	async put() { throw new Error("stub: put not used in dry-run"); },
	async save() { throw new Error("stub: save not used in dry-run"); },
	async readSvg() { return null; },
	getMetadata(id) { return stubStore.get(id) || null; },
	async load() { /* no-op */ },
};

async function main() {
	const tmpRoot = await mkdtemp(join(tmpdir(), "migrate-proof-"));
	try {
		const fixture = await makeLocalFixture(tmpRoot);

		// Capture stderr (the structured event stream) by intercepting
		// process.stderr.write for the duration of the run. The
		// production code uses the `log()` helper from src/logger.mjs
		// which writes to process.stderr — so spying on the stream
		// gives us the same byte-for-byte transcript the CLI would
		// produce.
		const realStderrWrite = process.stderr.write.bind(process.stderr);
		const stderrBuf = [];
		// @ts-ignore — vi-style spy without importing vitest
		process.stderr.write = (chunk) => {
			const text = typeof chunk === "string" ? chunk
				: Buffer.isBuffer(chunk) ? chunk.toString("utf-8")
				: String(chunk || "");
			stderrBuf.push(text);
			return true;
		};

		let result;
		try {
			result = await runMigration({
				env: {},
				sourceDir: "<data>",   // presentable in the proof artifact
				sourceStorage: fixture.storage,
				targetStorage: stubTarget,
				dryRun: true,
			});
		} finally {
			process.stderr.write = realStderrWrite;
		}

		// Build the proof transcript: the same shape the CLI writes
		// to stderr (one JSON object per line) + the summary on stdout.
		const stderrText = stderrBuf.join("");
		const stdoutText = formatSummary(result) + "\n";

		const lines = [
			"# bin/migrate-to-oss.mjs --dry-run proof transcript",
			"# Captured via the same `runMigration` code path the CLI runs,",
			"# against a 5-entry LocalFsStorage fixture (3 fresh+pinned,",
			"# 1 expired-but-pinned, 1 expired-and-unpinned) and a stub",
			"# OssStorage target. The 4 surviving entries are reported as",
			"# would-copy; 0 entries are written. Re-running the CLI",
			"# against a real MinIO bucket produces the same shape.",
			"#",
			"# Generated by tests/integration/migrate-to-oss-proofs/capture-dry-run.mjs",
			"#",
			"# --- stderr (structured event stream) ---",
			stderrText.trimEnd(),
			"",
			"# --- stdout (human summary line) ---",
			stdoutText.trimEnd(),
			"",
		];

		const { writeFile } = await import("node:fs/promises");
		await writeFile(PROOF_PATH, lines.join("\n"), "utf-8");

		// Also echo the proof to the capture script's stdout so the
		// `node ...capture-dry-run.mjs` invocation is self-documenting.
		process.stdout.write(lines.join("\n"));
	} finally {
		await rm(tmpRoot, { recursive: true, force: true });
	}
}

main().catch((e) => {
	process.stderr.write(`capture-dry-run: ${e?.stack || e?.message || e}\n`);
	process.exit(1);
});
